services:
  - type: web
    name: cisconnects
    env: node
    buildCommand: npm run build
    startCommand: node server.js
    pullRequestPreviewsEnabled: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

